cached:
  delay:
    max: 1000
    min: 1000
  filesize:
    max: 50
    min: 50
    scaler: 10
  objects: 50
  weight: 1
delay:
  max: 1000
  min: 1000
non_cached:
  delay:
    max: 1000
    min: 1000
  filesize:
    max: 50
    min: 50
    scaler: 10
  objects: 50
  weight: 1
percentage_cached: 90
