percentage_cached: 10
delay:
  min: 200
  max: 200
cached:
 weight: 20
 filesize:
  min: 10
  max: 10
  scaler: 10
 delay:
  min: 200
  max: 200
 objects: 200
non_cached:
 weight: 80
 filesize:
  min: 10
  max: 10
  scaler: 10
 delay:
  min: 200
  max: 200
 objects: 200
