percentage_cached: 10
delay:
  min: 400
  max: 600
cached:
 weight: 20
 filesize:
  min: 3000
  max: 3000
  scaler: 1000
 delay:
  min: 400
  max: 600
 objects: 50
non_cached:
 weight: 80
 filesize:
  min: 3000
  max: 3000
  scaler: 1000
 delay:
  min: 400
  max: 600
 objects: 50
